apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: weblog
  name: weblog

---
apiVersion: v1
data:
  LOG_FILE: app.log
  LOG_PATH: /var/log/app
  MAX_ENTRIES: "100"
kind: ConfigMap
metadata:
  name: log-config
  namespace: weblog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-logger
  name: web-logger
  namespace: weblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-logger
  strategy: {}
  template:
    metadata:
      labels:
        app: web-logger
    spec:
      volumes:
        - name: weblog
          emptyDir: {}
      initContainers:
        - name: dir-setup
          image: busybox
          volumeMounts:
            - name: weblog
              mountPath: /var/log/app
              readOnly: false
          env:
            - name: LOG_PATH
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: LOG_PATH
          command: ["sh", "-c", "mkdir -p $LOG_PATH && echo directory created by init at $date > $LOG_PATH/init.txt"]
      containers:
        - image: busybox
          name: app
          resources: {}
          volumeMounts:
            - name: weblog
              mountPath: /var/log/app
              readOnly: false
          envFrom:
            - configMapRef:
                name: log-config
          command: ["sh", "-c"]
          args:
            - |-
              counter=0
              echo "$counter $MAX_ENTRIES"
              while true; do
                if [[ $counter -ge $MAX_ENTRIES ]]; then
                  counter = 0
                  rm $LOG_PATH/$LOG_FILE
                fi
                echo {"pod":"$MY_POD_NAME","ip":"$MY_POD_IP","entry":$counter,"ts":"$(date)"} >> $LOG_PATH/$LOG_FILE
                counter=$((counter+1))
                sleep 2
              done
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - image: busybox
          name: log-shipper
          resources: {}
          volumeMounts:
            - name: weblog
              mountPath: /var/log/app
              readOnly: true
          envFrom:
            - configMapRef:
                name: log-config
          command: ["sh", "-c"]
          args:
            - |-
              file=$LOG_PATH/$LOG_FILE
              while [[ ! -e $file  ]]; do
                sleep 1
              done
              tail -f $file
status: {}
