apiVersion: v1
kind: Pod
metadata:
  labels:
    run: echo-pod
  name: echo-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do echo 'Hello from CKA'; sleep 5;done
    image: busybox
    name: echo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
