---
#  k run echo-pod --image busybox --restart=OnFailure --dry-run=client -o yaml  --command sh -- -c "while true; do echo 'Hello from CKA'; sleep 5;done" > 01.yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: echo-pod
  name: echo-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo 'Hello from CKA'; sleep 5;done
    image: busybox
    name: echo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
