apiVersion: v1
kind: Pod
metadata:
  labels:
    run: greeter
  name: greeter
spec:
  containers:
  - command: ["sh"]
    args:
    - -c
    - echo $(GREETING)
    env:
    - name: GREETING
      value: Kubernetes is fun
    image: busybox
    name: greeter
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
