---
apiVersion: v1
data:
  APP_ENV: production
  LOG_LEVEL: debug
kind: ConfigMap
metadata:
  name: app-config
  namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: config-reader
  name: config-reader
spec:
  containers:
  - image: busybox
    name: config-reader
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: config
      configMap:
status: {}
