apiVersion: v1
kind: Pod
metadata:
  labels:
    run: downward-env
  name: downward-env
spec:
  containers:
  - env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    image: busybox
    name: downward-env
    command: ["sleep", "1000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
