---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

labels:
  - pairs:
      stage: production
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  example.com/annotation: production

replicas:
  - name: nginx
    count: 3

namePrefix: prod-

nameSuffix: -v1
