apiVersion: v1
kind: Pod
metadata:
  labels:
    run: twirl
  name: twirl
  namespace: security
spec:
  containers:
  - image: curlimages/curl
    name: twirl
    resources: {}
    command: ["sleep", "3000"]
    volumeMounts:
      - name: cluster-token
        mountPath: /xxx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: audit-sa
  volumes:
    - name: cluster-token
      projected:
        sources:
          - serviceAccountToken:
              path: cluster-token
              expirationSeconds: 7200
status: {}
