---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - image: busybox
          name: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Name is : $NAME"
              sleep 10000
          ports:
            - containerPort: 5678
          resources: {}
          envFrom:
            - configMapRef:
                name: busybox-config
status: {}
