apiVersion: batch/v1
kind: Job
metadata:
  name: pi-calculator
spec:
  completions: 1
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - perl 
        - -Mbignum=bpi 
        - -wle 
        - "print bpi(2000)"
        image: perl:5.34
        name: pi-calculator
        resources: {}
      restartPolicy: Never
status: {}

# check with `k logs pi-caclculator-xxx`
# can invoke the shell and just pass the cmd as string
