---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-04-05T07:17:36Z"
  labels:
    kubernetes.io/metadata.name: maintenance
  name: maintenance
  resourceVersion: "14165"
  uid: 7d7ec003-c190-46ef-b9de-8ea63f98071f
spec:
  finalizers:
    - kubernetes
status:
  phase: Active

---
# k -n maintenance create job cleaner --from=cronjob/log-cleanup
apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-cleanup
  namespace: maintenance
spec:
  jobTemplate:
    metadata:
      name: log-cleanup
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - command: ["sh", "-c"]
              args:
                - |-
                  echo "Cleaning logs at $(date)"
              image: busybox
              name: log-cleanup
              resources: {}
          restartPolicy: OnFailure
  schedule: "0 0 * * *" # == @daily or @midnight
  timeZone: "Etc/UTC"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: true
status: {}
